### PR TITLE
Initialize multilingual and add Chinese pages

### PR DESCRIPTION
**Pull request by hililiwei**
Initialize the multilingual and i18n support, add Chinese pages.

image

image

image

Chinese index page:
image

In the current PR, I have only translated some pages. Once this PR is allowed, I will try to translate more pages into Chinese, such as spec.md\roadmap.md\join.md etc.

Change log:
1. Add directory `content.zh` as the root directory of Chinese documents.
2. The `config.toml` is modified to support multiple languages:
```
[languages]
  [languages.en-us]
    weight = 1
    languageName = 'English'
    contentDir = 'content'
  [languages.zh-cn]
    weight = 1
    languageName = '简体中文'
    contentDir = 'content.zh'
```
3. Add I18N-related files, including en-us.toml zh-cn.toml.
4. Change the string in header.html to the {{i18n XXX } method.
5. Add select box for  language in the upper right corner of the home page.

### CODE REVIEW

**Comment by hililiwei** [comment]
cc @samredai @jackye1995 @rdblue @kbendick, 😃

**Comment by hililiwei** [comment]
A `common.zh` directory needs to be added to the` iceberg repo` for translation in the iceberg repo, synchronized to the `content.zh/common` directory of the repo during release:
`cp -r <path to iceberg repo>/docs/common.zh landing-page/content.zh/common`

**Comment by openinx** [comment]
I think we don't need to introduce an extra Chinese version for the iceberg document. Because the current google translate technology can easily translate the English document to a Chinese page. Besides , we will need to sync each PR for the Chinese version and that makes lots of maintance burden for apache iceberg community.

I will plan to close this PR.  Thanks @hililiwei for the contribution.

**Comment by hililiwei** [comment]
Okay, got it. thanks

**Pull request closed without merging**
