### PR TITLE
Update latest docs to include branching/tagging and table migration docs

### PR DESCRIPTION
**Pull request by amogh-jahagirdar**
This change updates the latest iceberg-docs (1.2.1)  to include branching/tagging docs as well as table migration docs. Once this change is merged, the website will include these docs which is desired since these features have already been released for a while.

### CODE REVIEW

**Review by jackye1995 — APPROVED** [review]
thanks for the backport!

**Comment by jackye1995** [comment]
I see this is open against the `latest` branch. I think we need to open it against `1.2.1` branch, and once that is merged, the latest branch can be directly rebased based on 1.2.1. Could you update that config?

**Comment by jackye1995** [comment]
I guess we can also open another identical PR against 1.2.1. Let me know when you do that, I can merge at the same time.

**Comment by amogh-jahagirdar** [comment]
Sure I raised https://github.com/apache/iceberg-docs/pull/230 for the 1.2.1 branch

**Pull request merged**
