### PR TITLE
Docs: Update spark-3.0 removal

### PR DESCRIPTION
**Pull request by ajantha-bhat**
Follow up of https://github.com/apache/iceberg/pull/6093 for docs repo.

### CODE REVIEW

**Comment by ajantha-bhat** [comment]
cc: @hililiwei, we might have to do the same for flink 1.13 removal and 1.16 addition.

**Comment by hililiwei** [comment]
@ajantha-bhat Copy that, thx.

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
@ajantha-bhat can you fix the conflict?

**Comment by ajantha-bhat** [comment]
Rebased now. Thanks

**Review by singhpk234 — APPROVED** [review]

**Comment by gaborkaszab** [comment]
@Fokko @rdblue Should we merge this with the 1.1.0 release out now?

**Comment by gaborkaszab** [comment]
thanks @Fokko!

**Pull request merged**
