### PR TITLE
Blog: add new Cloudera blog to docs site

### PR DESCRIPTION
**Pull request by marton-bod**

### CODE REVIEW

**Comment by samredai** [comment]
LGTM, thanks @marton-bod!

**Review by pvary — APPROVED** [review]

**Comment by pvary** [comment]
@samredai: What is the process here? As an Iceberg committer can I merge the change?

**Comment by samredai** [comment]
@rdblue or @jackye1995 can confirm who has merge privileges. But as far as the process, once this is merged it will automatically be deployed and should be live within a few minutes.

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks, @marton-bod! And congratulations on the announcement!

**Comment by marton-bod** [comment]
Thanks a lot @rdblue for your help in getting us there!

**Pull request merged**
