### PR TITLE
Add Impala to config defined docs menu

### PR DESCRIPTION
**Pull request by samredai**
The recent iceberg-theme that was merged uses a Hugo config based menu. This adds the external link to the Impala docs. Since logos are no longer being used, this also removes the impala logo image from the repo.

cc: @pvary

### CODE REVIEW

**Review by pvary — APPROVED** [review]

**Comment by pvary** [comment]
@samredai: Shall we add a Hive menu item as well?

Also this seems off:

```
{ name = "Presto", url = "../../how-to-release" , weight = 500 },
```

**Comment by samredai** [comment]
@pvary yes and yes, thanks for catching that! Opening a PR now 👍

**Comment by samredai** [comment]
@pvary with respect to adding Hive, that actually has its own internal page so when [hive.md](https://github.com/apache/iceberg/blob/master/docs/hive.md) is copied over from the iceberg repo, it will automatically show up as an item in the leftnav. (Set by the `menu: main` in the front matter)

**Comment by pvary** [comment]
That's cool.

Maybe a link in the main menu would be good, somewhere between Presto,  Trinto and Impala.

**Pull request merged**
