### PR TITLE
Add javadoc directory and deployment job

### PR DESCRIPTION
**Pull request by samredai**
Since adding the `javadoc` directory includes a lot of files and is obfuscating any paired changes, I'm opening this PR that purely does the following:

- `cp -r` of `iceberg/site/docs/javadoc/0.12.1/` in the proper iceberg repo to a `javadoc` directory in the root of this repo
- Add a `deploy-javadoc` job that copies to a `/javadoc/<branch_name>` directory in the `asf-site` branch
- Adds `!javadoc/resources` to the `.gitignore` file so that this directory is not ignored (`resources` generally is a recommended ignore for hugo projects)

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
Is the idea that on every release we are going to run a cp -r of the java docs to here manually?

**Comment by rdblue** [comment]
@samredai is this deployed so I can take a quick look?

**Comment by rdblue** [comment]
Also, will you follow up with the old javadocs that are currently on the site?

**Comment by samredai** [comment]
@rdblue I just deployed this commit so you can see it in action [here](https://iceberg.redai.dev/). You should be able to test that the current javadoc links aren't broken, for example `https://iceberg.apache.org/javadoc/0.12.1/org/apache/iceberg/Table.html#expireSnapshots--` -> `s/apache.org/redai.dev` -> `https://iceberg.redai.dev/javadoc/0.12.1/org/apache/iceberg/Table.html#expireSnapshots--`.

Keep in mind that the javadocs links in the markdown pages will be broken for now. I'll fix that in a follow-up PR. That's because `../javadoc` will need to be changed to `../../../javadoc` (to account for the `docs/<version>` included in the versioned doc site.

As for the old javadocs, yes I can follow-up with adding those. It should be as simple as creating a branch for each of the versions and then updating the javadoc root directories in each branch to contain the corresponding javadoc.

**Comment by rdblue** [comment]
Thanks, @samredai! Those links were exactly what I was going to check.

**Pull request merged**
