### PR TITLE
Add blog about using iceberg for OLAP

### PR DESCRIPTION
**Pull request by lirui-apache**
Hey, I would like to share a blog about how we use iceberg for OLAP scenarios. We have been working on the platform for about two years and had built some solid use case with it.

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
Sorry needs a rebase since I just modified this blog list. We also probably need a different way of sharing blogs. This is becoming a bit unwieldy, thoughts @Fokko ?

**Review by szehon-ho — APPROVED** [review]
Yea this would be great to get in, I had read Chinese version earlier, glad to see its translated and to see the use-cases of Iceberg

**Comment by lirui-apache** [comment]
@RussellSpitzer @szehon-ho Thanks for the review. I have rebased the PR.

**Comment by szehon-ho** [comment]
Thanks @lirui-apache

**Pull request merged**
